package interfaceGrafica;

import repositorio.*;
import javax.swing.JOptionPane;
import modelos.*;

public class AlterarAtendimento extends javax.swing.JFrame {

	Atendimento atendimentoAlterar;

	public AlterarAtendimento(Atendimento atendimento) {
		initComponents();
		this.atendimentoAlterar = atendimento;
		txtCpfCliente.setText(this.atendimentoAlterar.getCpfCliente());
		txtDataHora.setText(this.atendimentoAlterar.getDataHora());
		txResolucao.setText(this.atendimentoAlterar.getResolucao());
		txtCodigoProduto.setText(this.atendimentoAlterar.getCodProduto());
		jTextArea3.setText(this.atendimentoAlterar.getDescricaoAtendimento());
	}

	public AlterarAtendimento() {
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblPrincipal = new javax.swing.JLabel();
		PainelAtendimento = new javax.swing.JPanel();
		lblCpfCliente = new javax.swing.JLabel();
		txtCpfCliente = new javax.swing.JTextField();
		txtDataHora = new javax.swing.JTextField();
		lblDataHora = new javax.swing.JLabel();
		txResolucao = new javax.swing.JTextField();
		lblResolucao = new javax.swing.JLabel();
		txtCodigoProduto = new javax.swing.JTextField();
		lblCodigoProduto = new javax.swing.JLabel();
		lblDescricao = new javax.swing.JLabel();
		spDescricao = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		btnSalvar = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lblPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		lblPrincipal.setText("Alterar Atendimento");

		PainelAtendimento.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Alterar de Atendimento"));

		lblCpfCliente.setText("Informe o CPF do cliente");

		lblDataHora.setText("Informe a Data e a Hora");

		lblResolucao.setText("Resolvido?");

		lblCodigoProduto.setText("Codigo do produto em questão");

		lblDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		lblDescricao.setText("Descrição");

		jTextArea3.setColumns(20);
		jTextArea3.setRows(5);
		spDescricao.setViewportView(jTextArea3);

		btnSalvar.setText("Salvar");
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});

		btnCancelar.setText("Cancelar");
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout PainelAtendimentoLayout = new javax.swing.GroupLayout(
				PainelAtendimento);
		PainelAtendimento.setLayout(PainelAtendimentoLayout);
		PainelAtendimentoLayout
				.setHorizontalGroup(PainelAtendimentoLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								PainelAtendimentoLayout
										.createSequentialGroup()
										.addGroup(
												PainelAtendimentoLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																PainelAtendimentoLayout
																		.createSequentialGroup()
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				PainelAtendimentoLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								lblCpfCliente)
																						.addComponent(
																								lblDataHora)
																						.addComponent(
																								lblResolucao)
																						.addComponent(
																								lblCodigoProduto))
																		.addGap(30,
																				30,
																				30)
																		.addGroup(
																				PainelAtendimentoLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								txtCodigoProduto,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								210,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								txResolucao,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								210,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								txtDataHora,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								210,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								txtCpfCliente,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								210,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																PainelAtendimentoLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				PainelAtendimentoLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								spDescricao,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								388,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								PainelAtendimentoLayout
																										.createSequentialGroup()
																										.addGap(160,
																												160,
																												160)
																										.addComponent(
																												lblDescricao)))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								PainelAtendimentoLayout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(btnSalvar)
										.addGap(55, 55, 55)
										.addComponent(btnCancelar)
										.addGap(116, 116, 116)));
		PainelAtendimentoLayout
				.setVerticalGroup(PainelAtendimentoLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								PainelAtendimentoLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												PainelAtendimentoLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																lblCpfCliente)
														.addComponent(
																txtCpfCliente,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												PainelAtendimentoLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																txtDataHora,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																lblDataHora))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												PainelAtendimentoLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																txResolucao,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																lblResolucao))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												PainelAtendimentoLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																lblCodigoProduto)
														.addComponent(
																txtCodigoProduto,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(lblDescricao)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												spDescricao,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												74,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addGroup(
												PainelAtendimentoLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(btnSalvar)
														.addComponent(
																btnCancelar))
										.addContainerGap(13, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(165,
																		165,
																		165)
																.addComponent(
																		lblPrincipal))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(29, 29,
																		29)
																.addComponent(
																		PainelAtendimento,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(27, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGap(14, 14, 14)
						.addComponent(lblPrincipal)
						.addGap(22, 22, 22)
						.addComponent(PainelAtendimento,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(21, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
		this.dispose();
	}// GEN-LAST:event_btnCancelarActionPerformed

	private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
		try {
			atendimentoAlterar.setCpfCliente(txtCpfCliente.getText());
			atendimentoAlterar.setDataHora(txtDataHora.getText());
			atendimentoAlterar.setResolucao(txResolucao.getText());
			atendimentoAlterar.setCodProduto(txtCodigoProduto.getText());
			atendimentoAlterar.setDescricaoAtendimento(jTextArea3.getText());
			// RepositorioCliente.obterInstancia().atualizar(clienteAlterar);
			RepositorioAtendimentoConexao.obterInstancia().atualizar(
					atendimentoAlterar);
			JOptionPane.showMessageDialog(null,
					"Atendimento alterado com sucesso");
			this.dispose();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());

		}
	}// GEN-LAST:event_btnSalvarActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					AlterarAtendimento.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					AlterarAtendimento.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					AlterarAtendimento.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					AlterarAtendimento.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AlterarAtendimento().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel PainelAtendimento;
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JLabel lblCodigoProduto;
	private javax.swing.JLabel lblCpfCliente;
	private javax.swing.JLabel lblDataHora;
	private javax.swing.JLabel lblDescricao;
	private javax.swing.JLabel lblPrincipal;
	private javax.swing.JLabel lblResolucao;
	private javax.swing.JScrollPane spDescricao;
	private javax.swing.JTextField txResolucao;
	private javax.swing.JTextField txtCodigoProduto;
	private javax.swing.JTextField txtCpfCliente;
	private javax.swing.JTextField txtDataHora;
	// End of variables declaration//GEN-END:variables
}
