package interfaceGrafica;

import SistemaXload.Modelos.Atendimento;
import SistemaXload.Repositorio.RepositorioAtendimentoConexao;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ConsultaAtendimento extends javax.swing.JFrame {

	private ArrayList<Atendimento> lista;

	public ConsultaAtendimento() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblPrincipal = new javax.swing.JLabel();
		painelAtendimentos = new javax.swing.JPanel();
		spAtendimentos = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		btnAtualizar = new javax.swing.JButton();
		btnNovo = new javax.swing.JButton();
		btnAlterar = new javax.swing.JButton();
		btnRemover = new javax.swing.JButton();
		btnMenuPrincipal = new javax.swing.JButton();
		btnFechar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lblPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		lblPrincipal.setText("Atendimentos");

		painelAtendimentos.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Consulta de Atendimentos"));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null },
						{ null, null, null, null, null },
						{ null, null, null, null, null },
						{ null, null, null, null, null } }, new String[] {
						"CPF Cliente", "Data e Hora", "Resolvido?",
						"Codigo Produto", "Descrição " }));
		spAtendimentos.setViewportView(jTable1);

		btnAtualizar.setText("Atualizar");
		btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAtualizarActionPerformed(evt);
			}
		});

		btnNovo.setText("Novo");
		btnNovo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnNovoActionPerformed(evt);
			}
		});

		btnAlterar.setText("Alterar");
		btnAlterar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAlterarActionPerformed(evt);
			}
		});

		btnRemover.setText("Remover");
		btnRemover.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRemoverActionPerformed(evt);
			}
		});

		btnMenuPrincipal.setText("Menu Principal");
		btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnMenuPrincipalActionPerformed(evt);
			}
		});

		btnFechar.setText("Fechar Janela");
		btnFechar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnFecharActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout painelAtendimentosLayout = new javax.swing.GroupLayout(
				painelAtendimentos);
		painelAtendimentos.setLayout(painelAtendimentosLayout);
		painelAtendimentosLayout
				.setHorizontalGroup(painelAtendimentosLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								painelAtendimentosLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												spAtendimentos,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												493,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								painelAtendimentosLayout
										.createSequentialGroup()
										.addGap(0, 0, Short.MAX_VALUE)
										.addGroup(
												painelAtendimentosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																btnAtualizar,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																btnMenuPrincipal,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addGap(38, 38, 38)
										.addComponent(btnNovo)
										.addGap(47, 47, 47)
										.addComponent(btnAlterar)
										.addGap(31, 31, 31)
										.addGroup(
												painelAtendimentosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																btnFechar,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																122,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																painelAtendimentosLayout
																		.createSequentialGroup()
																		.addGap(8,
																				8,
																				8)
																		.addComponent(
																				btnRemover)))
										.addGap(24, 24, 24)));
		painelAtendimentosLayout
				.setVerticalGroup(painelAtendimentosLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								painelAtendimentosLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												spAtendimentos,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												159,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addGroup(
												painelAtendimentosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																btnRemover)
														.addComponent(
																btnAlterar)
														.addComponent(btnNovo)
														.addComponent(
																btnAtualizar))
										.addGap(18, 18, 18)
										.addGroup(
												painelAtendimentosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																btnMenuPrincipal)
														.addComponent(btnFechar))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(23, 23,
																		23)
																.addComponent(
																		painelAtendimentos,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(232,
																		232,
																		232)
																.addComponent(
																		lblPrincipal)))
								.addContainerGap(25, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addComponent(lblPrincipal)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(painelAtendimentos,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(25, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNovoActionPerformed
		NovoAtendimento form = new NovoAtendimento();
		form.show();
	}// GEN-LAST:event_btnNovoActionPerformed

	private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnFecharActionPerformed
		this.dispose();
	}// GEN-LAST:event_btnFecharActionPerformed

	private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAtualizarActionPerformed
		DefaultTableModel modelo = new DefaultTableModel();
		modelo.setColumnIdentifiers(new String[] { "cpfCliente", "dataHora",
				"resolucao", "descricao", "descricaoAtendimento" });
		RepositorioAtendimentoConexao instancia = RepositorioAtendimentoConexao
				.obterInstancia();
		try {
			this.lista = instancia.listarTodos();
		} catch (Exception ex) {
			Logger.getLogger(ConsultaCliente.class.getName()).log(Level.SEVERE,
					null, ex);
		}
		for (int i = 0; i < lista.size(); i++) {
			modelo.addRow(new Object[] { this.lista.get(i).getCpfCliente(),
					this.lista.get(i).getDataHora(),
					this.lista.get(i).getResolucao(),
					this.lista.get(i).getCodProduto(),
					this.lista.get(i).getDescricaoAtendimento() });

		}
		jTable1.setModel(modelo);
	}// GEN-LAST:event_btnAtualizarActionPerformed

	private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAlterarActionPerformed
		AlterarAtendimento form = new AlterarAtendimento(this.lista.get(jTable1
				.getSelectedRow()));
		form.show();
	}// GEN-LAST:event_btnAlterarActionPerformed

	private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRemoverActionPerformed
		try {
			RepositorioAtendimentoConexao.obterInstancia().remover(
					this.lista.get(jTable1.getSelectedRow()));
			JOptionPane.showMessageDialog(null,
					"Atendimento excluido com sucesso");
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		}
	}// GEN-LAST:event_btnRemoverActionPerformed

	private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMenuPrincipalActionPerformed
		TelaPrincipal form = new TelaPrincipal();
		form.show();
		this.dispose();
	}// GEN-LAST:event_btnMenuPrincipalActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					ConsultaAtendimento.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					ConsultaAtendimento.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					ConsultaAtendimento.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					ConsultaAtendimento.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ConsultaAtendimento().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAlterar;
	private javax.swing.JButton btnAtualizar;
	private javax.swing.JButton btnFechar;
	private javax.swing.JButton btnMenuPrincipal;
	private javax.swing.JButton btnNovo;
	private javax.swing.JButton btnRemover;
	private javax.swing.JTable jTable1;
	private javax.swing.JLabel lblPrincipal;
	private javax.swing.JPanel painelAtendimentos;
	private javax.swing.JScrollPane spAtendimentos;
	// End of variables declaration//GEN-END:variables
}
