package interfaceGrafica;

import SistemaXload.Modelos.Produto;
import SistemaXload.Repositorio.RepositorioProdutoConexao;
import javax.swing.JOptionPane;

public class NovoProduto extends javax.swing.JFrame {

	/**
	 * Creates new form NovoProduto
	 */
	public NovoProduto() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		painelProdutos = new javax.swing.JPanel();
		lblCodigo = new javax.swing.JLabel();
		txtCodigo = new javax.swing.JTextField();
		lblDescricao = new javax.swing.JLabel();
		txtDescricao = new javax.swing.JTextField();
		lblPreco = new javax.swing.JLabel();
		txtPreco = new javax.swing.JTextField();
		btnSalvar = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		lblProducao = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		painelProdutos.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Cadastro de Produtos"));

		lblCodigo.setText("Codigo");

		lblDescricao.setText("Descrição");

		lblPreco.setText("Preço");

		btnSalvar.setText("Salvar");
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});

		btnCancelar.setText("Cancelar");
		btnCancelar.setName(""); // NOI18N
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout painelProdutosLayout = new javax.swing.GroupLayout(
				painelProdutos);
		painelProdutos.setLayout(painelProdutosLayout);
		painelProdutosLayout
				.setHorizontalGroup(painelProdutosLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								painelProdutosLayout
										.createSequentialGroup()
										.addGap(21, 21, 21)
										.addGroup(
												painelProdutosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(lblPreco)
														.addComponent(
																lblDescricao)
														.addComponent(lblCodigo))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												painelProdutosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																painelProdutosLayout
																		.createSequentialGroup()
																		.addComponent(
																				btnSalvar)
																		.addGap(44,
																				44,
																				44)
																		.addComponent(
																				btnCancelar))
														.addComponent(
																txtDescricao,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																223,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txtCodigo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																223,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txtPreco,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																223,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(20, Short.MAX_VALUE)));
		painelProdutosLayout
				.setVerticalGroup(painelProdutosLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								painelProdutosLayout
										.createSequentialGroup()
										.addGap(17, 17, 17)
										.addGroup(
												painelProdutosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(lblCodigo)
														.addComponent(
																txtCodigo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												painelProdutosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																lblDescricao)
														.addComponent(
																txtDescricao,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												painelProdutosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(lblPreco)
														.addComponent(
																txtPreco,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												painelProdutosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(btnSalvar)
														.addComponent(
																btnCancelar))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		lblProducao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		lblProducao.setText("Cadastro de Produtos");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(20, 20,
																		20)
																.addComponent(
																		painelProdutos,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(97, 97,
																		97)
																.addComponent(
																		lblProducao)))
								.addContainerGap(24, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(18, Short.MAX_VALUE)
						.addComponent(lblProducao)
						.addGap(18, 18, 18)
						.addComponent(painelProdutos,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(25, 25, 25)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
		this.dispose();
	}// GEN-LAST:event_btnCancelarActionPerformed

	private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
		try {
			Produto produto = new Produto();
			produto.setCodigo(txtCodigo.getText());
			produto.setDescricao(txtDescricao.getText());
			produto.setPreco(Float.parseFloat(txtPreco.getText()));
			RepositorioProdutoConexao.obterInstancia().inserir(produto);
			JOptionPane.showMessageDialog(null,
					"Produto cadastrado com sucesso");
			this.dispose();

		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		}
	}// GEN-LAST:event_btnSalvarActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NovoProduto.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NovoProduto.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NovoProduto.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NovoProduto.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NovoProduto().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JLabel lblCodigo;
	private javax.swing.JLabel lblDescricao;
	private javax.swing.JLabel lblPreco;
	private javax.swing.JLabel lblProducao;
	private javax.swing.JPanel painelProdutos;
	private javax.swing.JTextField txtCodigo;
	private javax.swing.JTextField txtDescricao;
	private javax.swing.JTextField txtPreco;
	// End of variables declaration//GEN-END:variables
}
