package interfaceGrafica;

import SistemaXload.Modelos.Atendimento;
import SistemaXload.Repositorio.RepositorioAtendimentoConexao;
import javax.swing.JOptionPane;

public class NovoAtendimento extends javax.swing.JFrame {

	public NovoAtendimento() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblPrincipal = new javax.swing.JLabel();
		painelAtendimento = new javax.swing.JPanel();
		lblCpfCliente = new javax.swing.JLabel();
		txtCpfCliente = new javax.swing.JTextField();
		txtDataHora = new javax.swing.JTextField();
		lblDataHora = new javax.swing.JLabel();
		txtResolucao = new javax.swing.JTextField();
		lblResolucao = new javax.swing.JLabel();
		txtCodigoProduto = new javax.swing.JTextField();
		lblCodigoProduto = new javax.swing.JLabel();
		lblDescricao = new javax.swing.JLabel();
		spDescricao = new javax.swing.JScrollPane();
		txtAreaDescricao = new javax.swing.JTextArea();
		btnSalvar = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		btnConsultaCliente = new javax.swing.JButton();
		btnConsultaProduto = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lblPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		lblPrincipal.setText("Cadastro Atendimento");

		painelAtendimento.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Cadastro de Atendimento"));

		lblCpfCliente.setText("Digite o CPF do cliente");

		lblDataHora.setText("Digite a Data e a Hora");

		lblResolucao.setText("Resolvido?");

		lblCodigoProduto.setText("Codigo do produto");

		lblDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		lblDescricao.setText("Descrição");

		txtAreaDescricao.setColumns(20);
		txtAreaDescricao.setRows(5);
		spDescricao.setViewportView(txtAreaDescricao);

		btnSalvar.setText("Salvar");
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});

		btnCancelar.setText("Cancelar");
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout painelAtendimentoLayout = new javax.swing.GroupLayout(
				painelAtendimento);
		painelAtendimento.setLayout(painelAtendimentoLayout);
		painelAtendimentoLayout
				.setHorizontalGroup(painelAtendimentoLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								painelAtendimentoLayout
										.createSequentialGroup()
										.addGap(62, 62, 62)
										.addComponent(
												btnSalvar,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												71,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(btnCancelar)
										.addGap(82, 82, 82))
						.addGroup(
								painelAtendimentoLayout
										.createSequentialGroup()
										.addGroup(
												painelAtendimentoLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																painelAtendimentoLayout
																		.createSequentialGroup()
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				painelAtendimentoLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								painelAtendimentoLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addComponent(
																												spDescricao)
																										.addGroup(
																												painelAtendimentoLayout
																														.createSequentialGroup()
																														.addGroup(
																																painelAtendimentoLayout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																		.addComponent(
																																				lblCpfCliente)
																																		.addComponent(
																																				lblDataHora)
																																		.addComponent(
																																				lblCodigoProduto)
																																		.addComponent(
																																				lblResolucao))
																														.addGap(14,
																																14,
																																14)
																														.addGroup(
																																painelAtendimentoLayout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				false)
																																		.addComponent(
																																				txtCpfCliente)
																																		.addComponent(
																																				txtCodigoProduto,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				226,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addComponent(
																																				txtResolucao,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				226,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))))
																						.addComponent(
																								txtDataHora,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								226,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																painelAtendimentoLayout
																		.createSequentialGroup()
																		.addGap(162,
																				162,
																				162)
																		.addComponent(
																				lblDescricao)))
										.addContainerGap(25, Short.MAX_VALUE)));
		painelAtendimentoLayout
				.setVerticalGroup(painelAtendimentoLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								painelAtendimentoLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												painelAtendimentoLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																lblCodigoProduto)
														.addGroup(
																painelAtendimentoLayout
																		.createSequentialGroup()
																		.addGroup(
																				painelAtendimentoLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								txtCpfCliente,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lblCpfCliente))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				painelAtendimentoLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								txtDataHora,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lblDataHora))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				painelAtendimentoLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								txtResolucao,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lblResolucao))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				txtCodigoProduto,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(18, 18, 18)
										.addComponent(lblDescricao)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												spDescricao,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												87, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												painelAtendimentoLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																btnCancelar)
														.addComponent(btnSalvar))
										.addContainerGap()));

		btnConsultaCliente.setText("Consulta Cliente");
		btnConsultaCliente
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						btnConsultaClienteActionPerformed(evt);
					}
				});

		btnConsultaProduto.setText("Consulta Produto");
		btnConsultaProduto
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						btnConsultaProdutoActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(29, 29,
																		29)
																.addComponent(
																		painelAtendimento,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(77, 77,
																		77)
																.addComponent(
																		btnConsultaCliente)
																.addGap(63, 63,
																		63)
																.addComponent(
																		btnConsultaProduto))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(154,
																		154,
																		154)
																.addComponent(
																		lblPrincipal)))
								.addContainerGap(49, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addComponent(lblPrincipal)
								.addGap(18, 18, 18)
								.addComponent(painelAtendimento,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														btnConsultaProduto)
												.addComponent(
														btnConsultaCliente))
								.addContainerGap(25, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
		this.dispose();
	}// GEN-LAST:event_btnCancelarActionPerformed

	private void btnConsultaClienteActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsultaClienteActionPerformed
		ConsultaCliente form = new ConsultaCliente();
		form.show();
	}// GEN-LAST:event_btnConsultaClienteActionPerformed

	private void btnConsultaProdutoActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsultaProdutoActionPerformed
		ConsultaProduto form = new ConsultaProduto();
		form.show();
	}// GEN-LAST:event_btnConsultaProdutoActionPerformed

	private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
		try {
			Atendimento atendimento = new Atendimento();
			atendimento.setCpfCliente(txtCpfCliente.getText());
			atendimento.setDataHora(txtDataHora.getText());
			atendimento.setResolucao(txtResolucao.getText());
			atendimento.setCodProduto(txtCodigoProduto.getText());
			atendimento.setDescricaoAtendimento(txtAreaDescricao.getText());
			RepositorioAtendimentoConexao.obterInstancia().inserir(atendimento);
			JOptionPane.showMessageDialog(null,
					"Atendimento cadastrado com sucesso");
			this.dispose();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		}
	}// GEN-LAST:event_btnSalvarActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NovoAtendimento.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NovoAtendimento.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NovoAtendimento.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NovoAtendimento.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NovoAtendimento().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnConsultaCliente;
	private javax.swing.JButton btnConsultaProduto;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JLabel lblCodigoProduto;
	private javax.swing.JLabel lblCpfCliente;
	private javax.swing.JLabel lblDataHora;
	private javax.swing.JLabel lblDescricao;
	private javax.swing.JLabel lblPrincipal;
	private javax.swing.JLabel lblResolucao;
	private javax.swing.JPanel painelAtendimento;
	private javax.swing.JScrollPane spDescricao;
	private javax.swing.JTextArea txtAreaDescricao;
	private javax.swing.JTextField txtCodigoProduto;
	private javax.swing.JTextField txtCpfCliente;
	private javax.swing.JTextField txtDataHora;
	private javax.swing.JTextField txtResolucao;
	// End of variables declaration//GEN-END:variables
}
