package interfaceGrafica;

public class TelaPrincipal extends javax.swing.JFrame {

	public TelaPrincipal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		painelPrincipal = new javax.swing.JPanel();
		btnCliente = new javax.swing.JButton();
		btnProdutos = new javax.swing.JButton();
		lblCliente = new javax.swing.JLabel();
		lblProduto = new javax.swing.JLabel();
		btnAtendimento = new javax.swing.JButton();
		lblAtendimento = new javax.swing.JLabel();
		lblXloadSystem = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		painelPrincipal
				.setBorder(javax.swing.BorderFactory
						.createTitledBorder("Clique nos botões para iniciar os módulos"));

		btnCliente.setText("Cliente");
		btnCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnClienteActionPerformed(evt);
			}
		});

		btnProdutos.setText("Produtos");
		btnProdutos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnProdutosActionPerformed(evt);
			}
		});

		lblCliente.setText("Alteração, consulta e cadastro.");

		lblProduto.setText("Alteração, consulta e cadastro.");

		btnAtendimento.setText("Atendimento");
		btnAtendimento.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAtendimentoActionPerformed(evt);
			}
		});

		lblAtendimento.setText("Alteração, consulta e cadastro.");

		javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(
				painelPrincipal);
		painelPrincipal.setLayout(painelPrincipalLayout);
		painelPrincipalLayout
				.setHorizontalGroup(painelPrincipalLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								painelPrincipalLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												painelPrincipalLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																painelPrincipalLayout
																		.createSequentialGroup()
																		.addGroup(
																				painelPrincipalLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								btnProdutos,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								93,
																								Short.MAX_VALUE)
																						.addComponent(
																								btnCliente,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				painelPrincipalLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								lblCliente,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								166,
																								Short.MAX_VALUE)
																						.addGroup(
																								painelPrincipalLayout
																										.createSequentialGroup()
																										.addComponent(
																												lblProduto)
																										.addGap(0,
																												0,
																												Short.MAX_VALUE))))
														.addGroup(
																painelPrincipalLayout
																		.createSequentialGroup()
																		.addComponent(
																				btnAtendimento)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				lblAtendimento)
																		.addContainerGap(
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))));
		painelPrincipalLayout
				.setVerticalGroup(painelPrincipalLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								painelPrincipalLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												painelPrincipalLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																btnCliente)
														.addComponent(
																lblCliente,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(16, 16, 16)
										.addGroup(
												painelPrincipalLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																lblProduto)
														.addComponent(
																btnProdutos))
										.addGap(18, 18, 18)
										.addGroup(
												painelPrincipalLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																lblAtendimento)
														.addComponent(
																btnAtendimento))
										.addContainerGap(21, Short.MAX_VALUE)));

		lblXloadSystem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		lblXloadSystem.setText("Xload System");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(119,
																		119,
																		119)
																.addComponent(
																		lblXloadSystem))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(28, 28,
																		28)
																.addComponent(
																		painelPrincipal,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(30, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(lblXloadSystem)
						.addGap(12, 12, 12)
						.addComponent(painelPrincipal,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(27, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClienteActionPerformed
		ConsultaCliente form = new ConsultaCliente();
		form.show();
	}// GEN-LAST:event_btnClienteActionPerformed

	private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnProdutosActionPerformed
		ConsultaProduto form = new ConsultaProduto();
		form.show();
	}// GEN-LAST:event_btnProdutosActionPerformed

	private void btnAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAtendimentoActionPerformed
		ConsultaAtendimento form = new ConsultaAtendimento();
		form.show();
	}// GEN-LAST:event_btnAtendimentoActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaPrincipal().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAtendimento;
	private javax.swing.JButton btnCliente;
	private javax.swing.JButton btnProdutos;
	private javax.swing.JLabel lblAtendimento;
	private javax.swing.JLabel lblCliente;
	private javax.swing.JLabel lblProduto;
	private javax.swing.JLabel lblXloadSystem;
	private javax.swing.JPanel painelPrincipal;
	// End of variables declaration//GEN-END:variables
}
